"""
This type stub file was generated by pyright.
"""

DEPRECATED_KEY_RE = ...
PREFIX_RE = ...
class Keyboard:
    """The current state of the keyboard.

    Each attribute represents a key. For example, ::

        keyboard.a

    is True if the 'A' key is depressed, and False otherwise.

    """
    _pressed = ...
    def __getattr__(self, kname): # -> bool:
        ...
    
    def __getitem__(self, k): # -> bool | Any:
        ...
    


keyboard = ...
