"""
This type stub file was generated by pyright.
"""

from .loaders import ResourceLoader

__all__ = ['rewind', 'stop', 'fadeout', 'set_volume', 'get_volume', 'get_pos', 'set_pos', 'play', 'queue', 'pause', 'unpause']
class _MusicLoader(ResourceLoader):
    """Pygame's music API acts as a singleton with one 'current' track.

    No objects are returned that represent different tracks, so this loader
    can't return anything useful. But it can perform all the path name
    validations and return the validated path, so that's what we do.

    This loader should not be exposed to the user.

    """
    EXTNS = ...
    TYPE = ...


_loader = ...
_paused = ...
def play(name): # -> None:
    """Play a music file from the music/ directory.

    The music will loop when it finishes playing.

    """
    ...

def play_once(name): # -> None:
    """Play a music file from the music/ directory."""
    ...

def queue(name): # -> None:
    """Queue a music file to follow the current track.

    This will load a music file and queue it. A queued music file will begin as
    soon as the current music naturally ends. If the current music is ever
    stopped or changed, the queued song will be lost.

    """
    ...

def is_playing(name): # -> bool:
    """Return True if the music is playing and not paused."""
    ...

def pause(): # -> None:
    """Temporarily stop playback of the music stream.

    Call `unpause()` to resume.

    """
    ...

def unpause(): # -> None:
    """Resume playback of the music stream after it has been paused."""
    ...

def fadeout(seconds): # -> None:
    """Fade out and eventually stop the music playback.

    :param seconds: The duration in seconds over which the sound will be faded
                    out. For example, to fade out over half a second, call
                    ``music.fadeout(0.5)``.

    """
    ...

rewind = ...
stop = ...
get_volume = ...
set_volume = ...
get_pos = ...
set_pos = ...
