"""
This type stub file was generated by pyright.
"""

def main(): # -> None:
    ...

def prepare_mod(mod): # -> None:
    """Prepare a module to run as a Pygame Zero program.

    mod is a loaded module object.

    This sets up things like screen, loaders and builtins, which need to be
    set before the module globals are run.

    """
    ...

def run_mod(mod): # -> None:
    """Run the module."""
    ...

