"""
This type stub file was generated by pyright.
"""

"""Identify WAV file formats.

This is used only to give better error messages in the event that a sound
file is not loadable by Pygame.

This is based on the 'magic' information for the 'file' command, at

https://github.com/file/file/blob/86e34444a26860f2ad9895a2d77cb16d1ca4c48b/magic/Magdir/riff

"""
class MagicReader:
    """Interface to reading the magic numbers in a file's header."""
    def __init__(self, path) -> None:
        ...
    
    def read_bytes(self, offset, length=...): # -> bytes:
        ...
    
    def read_leshort(self, offset): # -> Any:
        """Read an unsigned short at the given offset."""
        ...
    
    def read_lelong(self, offset): # -> Any:
        """Read an unsigned long at the given offset."""
        ...
    


CODECS = ...
def riff_wave(f, offset): # -> Generator[str | Any | None, Any, None]:
    """Read the WAVE format information."""
    ...

def riff_walk(f, offset): # -> list[str | Any | None] | list[str]:
    """Search chunks trying to find b'fmt '"""
    ...

def identify(path): # -> Literal['Ogg Vorbis', 'Unknown format (not RIFF WAVE)', 'Unknown RIFF format (not WAVE)']:
    ...

if __name__ == '__main__':
    tabstop = ...
